### ISSUE TITLE
Need to handle no --job-name provided

### ISSUE THREAD

**Issue by yfoo** [nauhpc/job_archive#1]
$ sbatch -p testq  <<EOF
#!/bin/sh
module list
EOF

resulted in the following dirt (ooh-err!)

ERROR:11 SLURM_JOB_NAME env not found - jobid: 12345 retrycnt: 7 elapse: 0.013476

**Comment by ddb79** [comment]
This is resolved by commit 66b4aba6c063e813a2a178251acf764c4aa43ae0
